import Head from 'next/head'
import Home from './home/home'
import Footer from '@/components/layout/Footer'

export default function index() {
  return (
    <div className='h-screen'>
      <Head>
        <title>food</title>
        <meta name="description" content="generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
    </div>    
  )
}
